# Generated by Django 3.2.5 on 2021-07-11 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_id', models.IntegerField()),
                ('mv_name', models.CharField(max_length=200)),
                ('mv_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
