# Generated by Django 3.2.5 on 2021-07-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='mv_url',
            new_name='mv_poster',
        ),
    ]
