# Generated by Django 3.2.5 on 2021-07-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_mv_url_favourites_mv_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='mv_over',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='mv_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='mv_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='mv_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='mv_poster',
            field=models.URLField(null=True),
        ),
    ]
